--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Paroxity/ParoxityVault
build-by-default: true
branches:
- master
projects:
  ParoxityVault:
    path: ""
    libs:
    - src: poggit/libasynql/libasynql
      version: ^3.3.0
    - src: SOF3/await-generator/await-generator
      version: ^3.0.0
...
